[client]
port=3333
default-character-set=utf8mb4

[mysql]
default-character-set=utf8mb4

[mysqld]
port=3333
basedir="C:/Program Files/MySQL/MySQL Server 8.4/"
datadir="C:/ProgramData/MySQL/MySQL Server 8.4/Data"
character-set-server=utf8mb4
default-storage-engine=INNODB

max_connections=200
max_connect_errors=10
sql-mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
